[package]
name = "droxyd"
version = "0.1.0"
edition = "2021"

# LEO added the following line:
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
